// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqvyhctrlljsafqchcjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxdnloY3RybGxqc2FmcWNoY2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzIzMjEsImV4cCI6MjA1ODQwODMyMX0.wLxLwc8f66zx11IIgo8xC2UGVv_qoZTy06ID1LB_7QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);